backend:
  name: git-gateway
  branch: master

# Uncomment for CMS testing
local_backend: true

site_url: https://yvonnechoi.ca
display_url: https://yvonnechoi.ca

# publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Testimonials",
              name: "testimonials",
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                  {
                    label: Position,
                    name: position,
                    widget: string,
                    required: false,
                  },
                ],
            }
          - { label: About, name: about, widget: text }
      - file: "src/content/biography/index.md"
        label: "Biography Page"
        name: "biography"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "biography-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/gallery/index.md"
        label: "Gallery Page"
        name: "gallery"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Photos",
              name: "photos",
              widget: list,
              fields:
                [
                  { label: "Image", name: "image", widget: "file" },
                ],
            }
      - file: "src/content/recordings/index.md"
        label: "Recordings Page"
        name: "recordings"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "recordings-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Audio",
              name: "audio",
              widget: list,
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Iframe", name: "iframe", widget: "string" },
                ],
            }
          - {
              label: "Solo Videos",
              name: "solo",
              widget: list,
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Link", name: "link", widget: "string" },
                ],
            }
          - {
              label: "Colab Videos",
              name: "colab",
              widget: list,
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Link", name: "link", widget: "string" },
                ],
              }
      - file: "src/content/concerts/index.md"
        label: "Concerts Page"
        name: "concerts"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "concerts-page",
            }
          - { label: "Title", name: title, widget: string }
          - {
              label: "Concerts",
              name: concerts,
              widget: list,
              fields:
                [
                  {
                    label: Month,
                    name: month,
                    widget: select,
                    options:
                      [
                        "Janurary",
                        "February",
                        "March",
                        "April",
                        "May",
                        "June",
                        "July",
                        "August",
                        "September",
                        "October",
                        "November",
                        "December",
                        "Dummy Month Do Not Delete"
                      ],
                  },
                  {
                    label: Concert,
                    name: concert,
                    widget: list,
                    fields:
                      [
                        { label: Concert Name, name: name, widget: string },
                        {
                          label: Concert Date,
                          name: date,
                          widget: datetime,
                          default: "",
                          date_format: "DD.MM",
                          time_format: "hh:mm",
                          format: "LLL",
                          picker_utc: false,
                        },
                        { label: Concert Venue, name: venue, widget: string },
                        {
                          label: Concert Location,
                          name: location,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
      - file: "src/content/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Services,
              name: services,
              widget: list,
              fields: [{ label: "Service", name: "service", widget: "string" }],
            }
          - {
              label: Specialties,
              name: specialties,
              widget: list,
              fields:
                [{ label: "Specialty", name: "specialty", widget: "string" }],
            }
